
import { RequireAuth } from "@/providers/auth/requireauth";
import { BookProvider } from "@/providers/book/index";
import { BookRequestProvider } from "@/providers/bookrequest";
import dynamic from "next/dynamic"; 

export const metadata = {
  title: 'Libhub',
  description: 'Generated by Next.js',
}

// const withAuth 

const DynamicRootLayout = dynamic(() => import('./layout'), { ssr: false });


const RootLayout = ({ children }: { children: React.ReactNode }) => {
  //const AuthenticatedComponent = RequireAuth(DynamicRootLayout);
  return (
    

    // ...

    //<AuthenticatedComponent>
      <BookRequestProvider>
        <BookProvider>
          <html lang="en">
            <head>
              <meta charSet="UTF-8" />
              <meta name="viewport" content="width=device-width, initial-scale=1.0" />
              <title>{metadata.title}</title>
              <meta name="description" content={metadata.description} />
            </head>
            <body style={{ margin: 0 }}>{children}</body>
          </html>
        </BookProvider>
      </BookRequestProvider>
    // </AuthenticatedComponent> */}
  );
}

export default RootLayout;
