import dynamic from "next/dynamic"; 
export const metadata = {
  title: 'Libhub',
  description: 'Generated by Next.js',
}

const DynamicRootLayout = dynamic(() => import('./layout'), { ssr: false });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style = {{margin: 0 }}>{children}</body>
    </html>
  )
}
